import type { CardTypesSource, SaivageConfigSource } from '../../schemas/index.js';
import { OVERSIGHT_ALLOWED_TOOL_NAMES } from '../../contracts/index.js';

const prompt = (reference: string) => ({ reference, compactable: true });

function deepFreeze<T>(value: T): T {
  if (value !== null && typeof value === 'object' && !Object.isFrozen(value)) {
    for (const nested of Object.values(value)) deepFreeze(nested);
    Object.freeze(value);
  }
  return value;
}

export function createClassicConfig(cardTypes: CardTypesSource): SaivageConfigSource {
  const agents: SaivageConfigSource['agents'] = {
    analyst: {
      prompt: prompt('analyst'),
      tools: [
        'create_card',
        'reorder_child',
        'reopen_card',
        'queue_notification',
        'get_status',
        'start_project',
        'pause_runtime',
        'resume_runtime',
        'stop_project',
        'restart_server',
        'navigate_workspace',
        'navigate_back',
        'show_config',
        'reconfigure',
        'read_runtime_events',
        'read_runtime_errors',
        'read_control_actions',
        'list_processes_tool',
        'list_agent_sessions',
        'read_agent_session',
        'cancel_card',
        'delete_card',
        'list_cards',
        'get_card',
        'get_tree',
        'list_card_versions',
        'get_card_version',
        'diff_card_versions',
        'read_record_version',
        'read',
        'view_image',
        'write',
        'edit',
        'glob',
        'grep',
        'apply_patch',
        'run_command',
        'wait_process',
        'kill_process',
        'websearch',
        'webfetch',
        'skill',
        'mcp_tool_call',
        'mcp_server_control',
        'mcp_tools',
      ],
      model_route: 'analyst',
      skills: true,
      session: 'global',
      can_create_children: true,
      record_writes: ['brief.md'],
    },
    oversight: {
      prompt: prompt('oversight'),
      tools: [...OVERSIGHT_ALLOWED_TOOL_NAMES],
      model_route: 'oversight',
      skills: false,
      session: 'global',
      can_create_children: false,
      record_writes: [],
    },
    planner: {
      prompt: prompt('planner'),
      tools: [
        'create_card',
        'edit_card',
        'cancel_card',
        'activate_card',
        'reopen_card',
        'reorder_child',
        'queue_notification',
        'list_cards',
        'get_card',
        'get_tree',
        'read',
        'write',
        'edit',
        'glob',
        'grep',
        'list_card_versions',
        'get_card_version',
        'diff_card_versions',
        'read_record_version',
        'websearch',
        'webfetch',
      ],
      model_route: 'planner',
      skills: false,
      session: 'card',
      can_create_children: true,
      record_writes: ['brief.md', 'status.md'],
    },
    reviewer: {
      prompt: prompt('reviewer'),
      tools: [
        'read',
        'view_image',
        'write',
        'edit',
        'glob',
        'grep',
        'list_card_versions',
        'get_card_version',
        'diff_card_versions',
        'read_record_version',
        'websearch',
        'webfetch',
        'skill',
      ],
      model_route: 'reviewer',
      skills: true,
      session: 'card',
      can_create_children: false,
      record_writes: ['review.md', 'review-*.md'],
    },
    executor: {
      prompt: prompt('executor'),
      tools: [
        'read',
        'view_image',
        'write',
        'edit',
        'glob',
        'grep',
        'apply_patch',
        'run_command',
        'wait_process',
        'kill_process',
        'list_card_versions',
        'get_card_version',
        'diff_card_versions',
        'read_record_version',
        'websearch',
        'webfetch',
        'skill',
        'mcp_tool_call',
        'mcp_server_control',
        'mcp_tools',
      ],
      model_route: 'executor',
      skills: true,
      session: 'card',
      can_create_children: false,
      record_writes: ['status.md'],
    },
  };
  const routes: SaivageConfigSource['models']['routes'] = {
    analyst: { candidates: ['gpt-6.1-sol'], temperature: 0.7, max_tokens: 4096 },
    oversight: { profile: 'planning', temperature: 0.2, max_tokens: 4096 },
    planner: { profile: 'planning', temperature: 0.7, max_tokens: 4096 },
    reviewer: { profile: 'review', temperature: 0.2, max_tokens: 4096 },
    executor: { candidates: ['gpt-6.1-sol'], temperature: 0.3, max_tokens: 8192 },
  };
  const config: SaivageConfigSource = {
    agents,
    analyst_agent: 'analyst',
    oversight: { enabled: true, agent: 'oversight', interval_seconds: 7200 },
    models: {
      routes,
      profiles: {
        planning: { preferred: ['gpt-5.6'], allowed: [] },
        review: { preferred: ['gpt-6.1-sol'], allowed: [] },
      },
      equivalents: [],
      failover: {},
    },
    providers: {},
    server: { host: '0.0.0.0', port: 8080 },
    compaction: {
      enabled: true,
      context_utilization_fraction: 0.8,
      trigger_fraction: 0.9,
      tail_fraction: 0.25,
      snap: 'keep_straddler_verbatim',
      summarizer_candidate: { provider: 'openai', account: null, model: 'gpt-6.1-sol' },
    },
    card_types: cardTypes,
  };
  return deepFreeze(config);
}
