import { afterEach,describe,expect,it,jest } from '@jest/globals';
import { existsSync,mkdirSync,mkdtempSync,readFileSync,readdirSync,rmSync,writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname,join,relative } from 'node:path';
import * as YAML from 'yaml';
import { run } from '../../src/cli.js';
import { DEFAULT_SAIVAGE_CONFIG,resolveSystemTemplate } from '../../src/config/system-templates/registry.js';
import { SAIVAGE_VERSION } from '../../src/version.js';
import { createResolvedConfigAuthority } from '../../src/config/resolved-config-authority.js';
import { createProjectIdentity,readProjectIdentity } from '../../src/persistence/project-identity.js';
import { readCard } from '../../src/persistence/card-files.js';

const roots:string[]=[];const cwd=process.cwd();afterEach(()=>{process.chdir(cwd);jest.restoreAllMocks();while(roots.length)rmSync(roots.pop()!,{recursive:true,force:true});});
function root(){const value=mkdtempSync(join(tmpdir(),'offline-workflow-'));roots.push(value);return value;}
function write(path:string,content:string){mkdirSync(dirname(path),{recursive:true});writeFileSync(path,content);}
function walkFiles(rootValue:string,current=rootValue):string[]{const files:string[]=[];for(const entry of readdirSync(current,{withFileTypes:true})){const path=join(current,entry.name);if(entry.isDirectory())files.push(...walkFiles(rootValue,path));else if(entry.isFile())files.push(relative(rootValue,path));}return files.sort();}
function assertTreeEqual(sourceRoot:string,actualRoot:string){expect(walkFiles(actualRoot)).toEqual(walkFiles(sourceRoot));for(const file of walkFiles(sourceRoot))expect(readFileSync(join(actualRoot,file))).toEqual(readFileSync(join(sourceRoot,file)));}
async function command(projectRoot:string,name:string,...args:string[]){process.chdir(projectRoot);await run(['node','saivage',name,...args]);}

describe('offline workflow compilation and publication',()=>{
  it('init materializes prompts and marker before the config YAML and validates before identity/card publication',async()=>{const projectRoot=root();jest.spyOn(console,'log').mockImplementation(()=>{});await command(projectRoot,'init');const configPath=join(projectRoot,'.saivage','saivage.yaml');const bytes=readFileSync(configPath);const source=YAML.parse(bytes.toString()) as Record<string,unknown>;expect(source).not.toHaveProperty('card_type_set');expect(source.card_types).toEqual(resolveSystemTemplate('classic').config.card_types);expect(JSON.parse(readFileSync(join(projectRoot,'.saivage','config','template.json'),'utf8'))).toEqual({template:'classic',saivage_version:SAIVAGE_VERSION});assertTreeEqual(resolveSystemTemplate('classic').promptRoot,join(projectRoot,'.saivage','config','prompts'));const effective=createResolvedConfigAuthority({path:configPath,interpolationEnvironment:{},projectRoot}).loadEffective();expect(effective.config).toEqual(DEFAULT_SAIVAGE_CONFIG);expect(readCard(projectRoot,'project')).toMatchObject({id:'project',type:'project'});const markerBytes=readFileSync(join(projectRoot,'.saivage','config','template.json'));await command(projectRoot,'init');expect(readFileSync(configPath)).toEqual(bytes);expect(readFileSync(join(projectRoot,'.saivage','config','template.json'))).toEqual(markerBytes);assertTreeEqual(resolveSystemTemplate('classic').promptRoot,join(projectRoot,'.saivage','config','prompts'));
    const invalidRoot=root();write(join(invalidRoot,'.saivage','saivage.yaml'),YAML.stringify({...structuredClone(DEFAULT_SAIVAGE_CONFIG),unknown_old_contract:true}));await expect(command(invalidRoot,'init')).rejects.toThrow(/Configuration validation failed/);expect(readProjectIdentity(invalidRoot)).toBeNull();expect(existsSync(join(invalidRoot,'.saivage','cards'))).toBe(false);
  });

  it('init --profile classic-typed materializes the 51-file closure and its marker',async()=>{const projectRoot=root();jest.spyOn(console,'log').mockImplementation(()=>{});await command(projectRoot,'init','--profile','classic-typed');const template=resolveSystemTemplate('classic-typed');const source=YAML.parse(readFileSync(join(projectRoot,'.saivage','saivage.yaml')).toString()) as Record<string,unknown>;expect(source.card_types).toEqual(template.config.card_types);expect(JSON.parse(readFileSync(join(projectRoot,'.saivage','config','template.json'),'utf8'))).toEqual({template:'classic-typed',saivage_version:SAIVAGE_VERSION});expect(walkFiles(join(projectRoot,'.saivage','config','prompts'))).toHaveLength(51);assertTreeEqual(template.promptRoot,join(projectRoot,'.saivage','config','prompts'));const effective=createResolvedConfigAuthority({path:join(projectRoot,'.saivage','saivage.yaml'),interpolationEnvironment:{},projectRoot}).loadEffective();expect([...effective.workflows.cardTypes.get('code')!.states.keys()]).toContain('node:green');
  });

  it('init --profile with an unknown name fails before any write',async()=>{const projectRoot=root();jest.spyOn(console,'log').mockImplementation(()=>{});await expect(command(projectRoot,'init','--profile','nope')).rejects.toThrow(/Unknown template 'nope'. Available templates: classic, classic-typed/);expect(existsSync(join(projectRoot,'.saivage','saivage.yaml'))).toBe(false);expect(existsSync(join(projectRoot,'.saivage','config','prompts'))).toBe(false);expect(existsSync(join(projectRoot,'.saivage','config','template.json'))).toBe(false);expect(readProjectIdentity(projectRoot)).toBeNull();expect(existsSync(join(projectRoot,'.saivage','cards'))).toBe(false);
  });

  it('config-absent re-init completes a partial tree without clobbering operator overrides',async()=>{const projectRoot=root();jest.spyOn(console,'log').mockImplementation(()=>{});const operatorOverride='OPERATOR ANALYST {{vocabularySnippet}}';write(join(projectRoot,'.saivage','config','prompts','agents','_shared','analyst.md'),operatorOverride);write(join(projectRoot,'.saivage','config','prompts','operators-extra.md'),'operator file');await command(projectRoot,'init');const template=resolveSystemTemplate('classic');const promptsRoot=join(projectRoot,'.saivage','config','prompts');expect(readFileSync(join(promptsRoot,'agents','_shared','analyst.md'),'utf8')).toBe(operatorOverride);expect(readFileSync(join(promptsRoot,'operators-extra.md'),'utf8')).toBe('operator file');const materialized=new Set(walkFiles(promptsRoot));for(const file of walkFiles(template.promptRoot))expect(materialized.has(file)).toBe(true);expect(walkFiles(promptsRoot)).toHaveLength(15);
    rmSync(join(projectRoot,'.saivage','saivage.yaml'));rmSync(join(promptsRoot,'process','_shared'),{recursive:true,force:true});writeFileSync(join(promptsRoot,'agents','_shared','analyst.md'),'operator edited');await command(projectRoot,'init');expect(readFileSync(join(promptsRoot,'agents','_shared','analyst.md'),'utf8')).toBe('operator edited');expect(existsSync(join(promptsRoot,'process','_shared','plan.md'))).toBe(true);expect(existsSync(join(projectRoot,'.saivage','saivage.yaml'))).toBe(true);expect(JSON.parse(readFileSync(join(projectRoot,'.saivage','config','template.json'),'utf8'))).toEqual({template:'classic',saivage_version:SAIVAGE_VERSION});expect(createResolvedConfigAuthority({path:join(projectRoot,'.saivage','saivage.yaml'),interpolationEnvironment:{},projectRoot}).loadEffective().config).toEqual(DEFAULT_SAIVAGE_CONFIG);
  });

  it('preserves exact pre-existing explicit-map bytes and uses their custom bootstrap definition',async()=>{const projectRoot=root();const config=structuredClone(DEFAULT_SAIVAGE_CONFIG);config.card_types.project!.records['charter.md']={...config.card_types.project!.records['brief.md']!,bootstrap:true};delete config.card_types.project!.records['brief.md'];const configPath=join(projectRoot,'.saivage','saivage.yaml');write(configPath,YAML.stringify(config));const bytes=readFileSync(configPath);jest.spyOn(console,'log').mockImplementation(()=>{});await command(projectRoot,'init');expect(readFileSync(configPath)).toEqual(bytes);expect(existsSync(join(projectRoot,'.saivage','cards','project','record-charter.jsonl'))).toBe(true);expect(existsSync(join(projectRoot,'.saivage','cards','project','record-brief.jsonl'))).toBe(false);expect(existsSync(join(projectRoot,'.saivage','config','prompts'))).toBe(false);expect(existsSync(join(projectRoot,'.saivage','config','template.json'))).toBe(false);
  });

  it('reset and start --create-runtime reject absent config before deleting or publishing generated state',async()=>{const projectRoot=root();createProjectIdentity(projectRoot,'offline-test');const marker=join(projectRoot,'.saivage','cards','retained.bin');write(marker,'retained');jest.spyOn(console,'log').mockImplementation(()=>{});await expect(command(projectRoot,'reset')).rejects.toThrow(/Configuration not found/);expect(readFileSync(marker,'utf8')).toBe('retained');const startRoot=root();createProjectIdentity(startRoot,'start-test');await expect(command(startRoot,'start','--project-root',startRoot,'--create-runtime')).rejects.toThrow(/Configuration validation failed/);expect(existsSync(join(startRoot,'.saivage','cards'))).toBe(false);});
});
