import { afterEach,describe,expect,it } from '@jest/globals';
import { mkdtempSync,readFileSync,rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createTestConfigAuthority } from '../helpers/project-config.js';
import { TEST_SAIVAGE_CONFIG } from '../helpers/test-saivage-config.js';
import { DEFAULT_SAIVAGE_CONFIG } from '../../src/agents/default-workflow-config.js';
import { BUNDLED_CARD_TYPE_SETS, resolveCardTypeSelection } from '../../src/config/card-type-sets/registry.js';
import { saivageConfigSchema } from '../../src/schemas/saivage-config.js';
import { MINIMAL_CARD_TYPE_SET } from '../fixtures/card-type-sets/minimal.js';
import { EXPECTED_SPECIALIZED_CARD_TYPES } from '../fixtures/card-type-sets/specialized.js';

const roots:string[]=[];afterEach(()=>{while(roots.length)rmSync(roots.pop()!,{recursive:true,force:true});});
function root(){const value=mkdtempSync(join(tmpdir(),'resolved-config-current-'));roots.push(value);return value;}

describe('restart-only resolved configuration authority',()=>{
  it('resolves omitted, standard, and explicit current definitions to the same effective configuration',()=>{const globals=structuredClone(DEFAULT_SAIVAGE_CONFIG) as Record<string,unknown>;delete globals.card_types;const omitted=createTestConfigAuthority(root(),{config:globals}).loadEffective();const selected=createTestConfigAuthority(root(),{config:{...globals,card_type_set:'standard'}}).loadEffective();const explicit=createTestConfigAuthority(root(),{config:DEFAULT_SAIVAGE_CONFIG}).loadEffective();expect(omitted.config).toEqual(DEFAULT_SAIVAGE_CONFIG);expect(selected.config).toEqual(DEFAULT_SAIVAGE_CONFIG);expect(explicit.config).toEqual(DEFAULT_SAIVAGE_CONFIG);expect(omitted.workflows.cardTypeVocabulary).toEqual(explicit.workflows.cardTypeVocabulary);expect([...selected.workflows.cardTypes.keys()]).toEqual([...explicit.workflows.cardTypes.keys()]);});
  it('keeps fixture selection in the pure resolver and production authority closed over bundled sets',()=>{const globals=structuredClone(DEFAULT_SAIVAGE_CONFIG) as Record<string,unknown>;delete globals.card_types;const source=saivageConfigSchema.parse({...globals,card_type_set:'minimal'});const resolved=resolveCardTypeSelection(source,[MINIMAL_CARD_TYPE_SET]);expect(resolved.card_types).toEqual(MINIMAL_CARD_TYPE_SET.cardTypes);resolved.card_types.project!.permitted_child_types.push('local-mutation');expect(MINIMAL_CARD_TYPE_SET.cardTypes.project!.permitted_child_types).toEqual([]);expect(()=>resolveCardTypeSelection(source,[MINIMAL_CARD_TYPE_SET,MINIMAL_CARD_TYPE_SET])).toThrow(/Duplicate card type set 'minimal'/);expect(()=>createTestConfigAuthority(root(),{config:{...globals,card_type_set:'minimal'}}).loadEffective()).toThrow(/Unknown card_type_set 'minimal'/);expect(BUNDLED_CARD_TYPE_SETS.map(({name})=>name)).toEqual(['standard','specialized']);});
  it('selects a complete immutable-cloned specialized map without changing the default',()=>{const globals=structuredClone(DEFAULT_SAIVAGE_CONFIG) as Record<string,unknown>;delete globals.card_types;const specialized=createTestConfigAuthority(root(),{config:{...globals,card_type_set:'specialized'}}).loadEffective();expect(specialized.config.card_types).toEqual(EXPECTED_SPECIALIZED_CARD_TYPES);expect(specialized.workflows.cardTypeVocabulary).toEqual(['project','goal','architecture','code','test','doc','data','research','ops']);specialized.config.card_types.project!.permitted_child_types.pop();expect(BUNDLED_CARD_TYPE_SETS.find(({name})=>name==='specialized')!.cardTypes.project!.permitted_child_types).toHaveLength(8);expect(createTestConfigAuthority(root(),{config:globals}).loadEffective().config).toEqual(DEFAULT_SAIVAGE_CONFIG);});
  it('rejects unknown and mutually exclusive source selection without fallback or merge',()=>{const globals=structuredClone(DEFAULT_SAIVAGE_CONFIG) as Record<string,unknown>;delete globals.card_types;expect(()=>createTestConfigAuthority(root(),{config:{...globals,card_type_set:'unknown'}}).loadEffective()).toThrow(/Unknown card_type_set 'unknown'/);expect(()=>createTestConfigAuthority(root(),{config:{...globals,card_type_set:'standard',card_types:DEFAULT_SAIVAGE_CONFIG.card_types}}).loadEffective()).toThrow(/mutually exclusive/);});
  it('preserves explicit nested model-equivalence arrays exactly',()=>{const config=structuredClone(TEST_SAIVAGE_CONFIG);config.models.equivalents=[['base-model','equivalent-model'],['other-model']];const effective=createTestConfigAuthority(root(),{config}).loadEffective();expect(effective.config.models.equivalents).toEqual([['base-model','equivalent-model'],['other-model']]);});
  it('rejects a legacy string-valued model-equivalence mapping at the selected YAML boundary',()=>{const config={...structuredClone(TEST_SAIVAGE_CONFIG),models:{...structuredClone(TEST_SAIVAGE_CONFIG.models),equivalents:{'base-model':'equivalent-model'}}};const authority=createTestConfigAuthority(root(),{config});expect(()=>authority.loadEffective()).toThrow(/Configuration validation failed: models\/equivalents:/);});
  it('rejects a complete model-equivalence mapping when one member was formerly discarded',()=>{const config={...structuredClone(TEST_SAIVAGE_CONFIG),models:{...structuredClone(TEST_SAIVAGE_CONFIG.models),equivalents:{'base-model':['equivalent-model'],malformed:7}}};const authority=createTestConfigAuthority(root(),{config});expect(()=>authority.loadEffective()).toThrow(/Configuration validation failed: models\/equivalents:/);});
  it('validates the complete candidate before replacement and never mutates the current compiled artifact',()=>{const projectRoot=root();const authority=createTestConfigAuthority(projectRoot);const current=authority.loadEffective();const result=authority.applyChange({kind:'set_agent_model_route',agent:'analyst',modelRoute:'executor'});expect(result).toMatchObject({success:true,requires_restart:true});expect(current.workflows.analyst.modelRoute).toBe('analyst');expect(authority.loadEffective().workflows.analyst.modelRoute).toBe('executor');expect(current.workflows).not.toBe(authority.loadEffective().workflows);});
  it('leaves exact file bytes unchanged for unknown agents, routes, and failover candidates',()=>{const projectRoot=root();const authority=createTestConfigAuthority(projectRoot);const before=readFileSync(authority.path);expect(authority.applyChange({kind:'set_agent_model_route',agent:'missing',modelRoute:'executor'}).success).toBe(false);expect(readFileSync(authority.path)).toEqual(before);expect(authority.applyChange({kind:'set_model_failover',forModel:'missing-model',orderedFailoverModels:[]}).success).toBe(false);expect(readFileSync(authority.path)).toEqual(before);});
});
