import { afterEach,describe,expect,it } from '@jest/globals';
import { cpSync,mkdtempSync,readFileSync,rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createTestConfigAuthority } from '../helpers/project-config.js';
import { TEST_SAIVAGE_CONFIG } from '../helpers/test-saivage-config.js';
import { specializedCardTypes } from '../helpers/specialized-config.js';
import { DEFAULT_SAIVAGE_CONFIG, resolveSystemTemplate } from '../../src/config/system-templates/registry.js';

const roots:string[]=[];afterEach(()=>{while(roots.length)rmSync(roots.pop()!,{recursive:true,force:true});});
function root(){const value=mkdtempSync(join(tmpdir(),'resolved-config-current-'));roots.push(value);return value;}
function materializeClassicTypedPrompts(projectRoot:string){cpSync(resolveSystemTemplate('classic-typed').promptRoot,join(projectRoot,'.saivage','config','prompts'),{recursive:true});}

describe('restart-only resolved configuration authority',()=>{
  it('resolves omitted and explicit classic definitions to the same effective configuration',()=>{const globals=structuredClone(DEFAULT_SAIVAGE_CONFIG) as Record<string,unknown>;delete globals.card_types;const omitted=createTestConfigAuthority(root(),{config:globals}).loadEffective();const explicit=createTestConfigAuthority(root(),{config:DEFAULT_SAIVAGE_CONFIG}).loadEffective();expect(omitted.config).toEqual(DEFAULT_SAIVAGE_CONFIG);expect(explicit.config).toEqual(DEFAULT_SAIVAGE_CONFIG);expect(omitted.workflows.cardTypeVocabulary).toEqual(explicit.workflows.cardTypeVocabulary);expect([...omitted.workflows.cardTypes.keys()]).toEqual([...explicit.workflows.cardTypes.keys()]);});
  it('selects a complete immutable-cloned specialized map without changing the default',()=>{const projectRoot=root();materializeClassicTypedPrompts(projectRoot);const globals=structuredClone(DEFAULT_SAIVAGE_CONFIG) as Record<string,unknown>;delete globals.card_types;const specialized=createTestConfigAuthority(projectRoot,{config:{...globals,card_types:specializedCardTypes()}}).loadEffective();expect(specialized.config.card_types).toEqual(resolveSystemTemplate('classic-typed').config.card_types);expect(specialized.workflows.cardTypeVocabulary).toEqual(['project','goal','architecture','code','test','doc','data','research','ops']);specialized.config.card_types.project!.permitted_child_types.pop();expect(resolveSystemTemplate('classic-typed').config.card_types!.project!.permitted_child_types).toHaveLength(8);expect(createTestConfigAuthority(root(),{config:globals}).loadEffective().config).toEqual(DEFAULT_SAIVAGE_CONFIG);});
  it('rejects the deleted card_type_set selector as an unknown source key without fallback or merge',()=>{const globals=structuredClone(DEFAULT_SAIVAGE_CONFIG) as Record<string,unknown>;delete globals.card_types;expect(()=>createTestConfigAuthority(root(),{config:{...globals,card_type_set:'standard'}}).loadEffective()).toThrow(/card_type_set/);expect(()=>createTestConfigAuthority(root(),{config:{...globals,card_type_set:'unknown'}}).loadEffective()).toThrow(/card_type_set/);expect(()=>createTestConfigAuthority(root(),{config:{...globals,card_type_set:'standard',card_types:structuredClone(DEFAULT_SAIVAGE_CONFIG.card_types)}}).loadEffective()).toThrow(/card_type_set/);});
  it('preserves explicit nested model-equivalence arrays exactly',()=>{const config=structuredClone(TEST_SAIVAGE_CONFIG);config.models.equivalents=[['base-model','equivalent-model'],['other-model']];const effective=createTestConfigAuthority(root(),{config}).loadEffective();expect(effective.config.models.equivalents).toEqual([['base-model','equivalent-model'],['other-model']]);});
  it('rejects a legacy string-valued model-equivalence mapping at the selected YAML boundary',()=>{const config={...structuredClone(TEST_SAIVAGE_CONFIG),models:{...structuredClone(TEST_SAIVAGE_CONFIG.models),equivalents:{'base-model':'equivalent-model'}}};const authority=createTestConfigAuthority(root(),{config});expect(()=>authority.loadEffective()).toThrow(/Configuration validation failed: models\/equivalents:/);});
  it('rejects a complete model-equivalence mapping when one member was formerly discarded',()=>{const config={...structuredClone(TEST_SAIVAGE_CONFIG),models:{...structuredClone(TEST_SAIVAGE_CONFIG.models),equivalents:{'base-model':['equivalent-model'],malformed:7}}};const authority=createTestConfigAuthority(root(),{config});expect(()=>authority.loadEffective()).toThrow(/Configuration validation failed: models\/equivalents:/);});
  it('validates the complete candidate before replacement and never mutates the current compiled artifact',()=>{const projectRoot=root();const authority=createTestConfigAuthority(projectRoot);const current=authority.loadEffective();const result=authority.applyChange({kind:'set_agent_model_route',agent:'analyst',modelRoute:'executor'});expect(result).toMatchObject({success:true,requires_restart:true});expect(current.workflows.analyst.modelRoute).toBe('analyst');expect(authority.loadEffective().workflows.analyst.modelRoute).toBe('executor');expect(current.workflows).not.toBe(authority.loadEffective().workflows);});
  it('leaves exact file bytes unchanged for unknown agents, routes, and failover candidates',()=>{const projectRoot=root();const authority=createTestConfigAuthority(projectRoot);const before=readFileSync(authority.path);expect(authority.applyChange({kind:'set_agent_model_route',agent:'missing',modelRoute:'executor'}).success).toBe(false);expect(readFileSync(authority.path)).toEqual(before);expect(authority.applyChange({kind:'set_model_failover',forModel:'missing-model',orderedFailoverModels:[]}).success).toBe(false);expect(readFileSync(authority.path)).toEqual(before);});
});
