import { argKeys, asRecord, cardPart, describeCardOutcome, describeJsonlTail, formatBytes, oneLine, pathParts, str, textPart } from './helpers';
import type { CallPresenter, ResultPresenter } from './types';

export const callPresenters: Record<string, CallPresenter> = {
  read: (a) => ({ icon: '📖', headline: pathParts(a.path) }),
  glob: (a) => ({ icon: '📂', headline: pathParts(a.directory ?? '.'), detail: textPart(str(a.pattern ?? '*')) }),
  grep: (a) => ({ icon: '🔎', headline: textPart(str(a.pattern), 80), detail: pathParts(a.path ?? '.') }),
  write: (a) => ({ icon: '✏️', headline: pathParts(a.path), detail: str(a.content) ? textPart(`${str(a.content).length} chars`) : undefined }),
  edit: (a) => ({ icon: '✎', headline: pathParts(a.path), detail: textPart('replace text') }),
  apply_patch: () => ({ icon: '🩹', headline: textPart('apply patch') }),
  websearch: (a) => ({ icon: '🌐', headline: textPart(str(a.query), 80) }),
  webfetch: (a) => ({ icon: '🌐', headline: textPart(str(a.url), 80) }),
  run_command: (a) => ({ icon: '⚡', headline: textPart(a.command, 80) }),
  wait_process: (a) => ({ icon: '⏳', headline: textPart(`process ${str(a.process_id)}`) }),
  kill_process: (a) => ({ icon: '🛑', headline: textPart(`process ${str(a.process_id)}`) }),
  activate_card: (a) => ({ icon: '▶', headline: cardPart(a.cardId) }),
  cancel_card: (a) => ({ icon: '⏹', headline: cardPart(a.cardId) }),
  delete_card: (a) => ({ icon: '🗑', headline: cardPart(a.cardId ?? a.id) }),
  create_card: (a) => ({ icon: '➕', headline: textPart(oneLine(a.title, 64) || (str(a.type) ? `${str(a.type)} card` : 'new card')), detail: [...textPart(str(a.type)), ...cardPart(a.parent, 'parent')] }),
  edit_card: (a) => ({ icon: '✎', headline: cardPart(a.id), detail: textPart(Object.keys(a).filter((key) => key !== 'id').join(', ')).length ? textPart(`change ${Object.keys(a).filter((key) => key !== 'id').join(', ')}`) : undefined }),
  emit_result: (a) => ({ icon: '✅', headline: textPart(str(a.summary ?? a.status ?? 'terminal result'), 96), detail: str(a.status) ? textPart(str(a.status)) : undefined }),
  move_card: (a) => ({ icon: '↳', headline: [...cardPart(a.id), ...textPart('→'), ...cardPart(a.newParent, 'root')] }),
  get_card: (a) => ({ icon: '🔎', headline: cardPart(a.id) }),
  list_cards: (a) => ({ icon: '🔎', headline: textPart(Object.entries(a).filter(([, value]) => value !== undefined && value !== null && value !== '').map(([key, value]) => `${key}=${str(value)}`).join(' · ') || 'all cards') }),
  get_tree: (a) => ({ icon: '🌳', headline: textPart(a.rootId ? `subtree ${str(a.rootId)}` : 'project tree') }),
  get_status: () => ({ icon: '📊', headline: textPart('project status') }),
  get_card_output: (a) => ({ icon: '🖥', headline: cardPart(a.cardId), detail: a.lines ? textPart(`last ${str(a.lines)} lines`) : undefined }),
  add_note: (a) => ({ icon: '📝', headline: cardPart(a.cardId), detail: textPart([str(a.kind), oneLine(a.content, 96)].filter(Boolean).join(' · ')) }),
  list_notes: (a) => ({ icon: '📋', headline: cardPart(a.cardId) }),
  get_note: (a) => ({ icon: '📋', headline: textPart(`note ${str(a.noteId)} on ${str(a.cardId)}`) }),
  mark_note_handled: (a) => ({ icon: '✓', headline: textPart(`note ${str(a.noteId)}`) }),
  read_runtime_events: (a) => ({ icon: '📜', headline: textPart(`events × ${str(a.limit ?? 50)}${a.kind ? ` [${str(a.kind)}]` : ''}`) }),
  read_runtime_errors: (a) => ({ icon: '🩺', headline: textPart(`errors × ${str(a.limit ?? 50)}`) }),
  read_control_actions: (a) => ({ icon: '🧭', headline: textPart(`control actions × ${str(a.limit ?? 50)}`) }),
  list_processes_tool: (a) => ({ icon: '⚙', headline: textPart(a.status || a.cardId ? `filter ${argKeys(a)}` : 'all processes') }),
  list_agent_sessions: () => ({ icon: '👥', headline: textPart('agent sessions') }),
  read_agent_session: (a) => ({ icon: '🧵', headline: textPart(`session ${str(a.sessionId)}`) }),
  pause_runtime: () => ({ icon: '⏸', headline: textPart('pause runtime') }),
  resume_runtime: () => ({ icon: '▶', headline: textPart('resume runtime') }),
  navigate_workspace: (a) => ({ icon: '🧭', headline: textPart(str(a.target ?? a.path ?? a.id ?? 'workspace')) }),
  navigate_back: () => ({ icon: '↩', headline: textPart('navigate back') }),
  queue_notification: (a) => ({ icon: '🔔', headline: textPart(str(a.message ?? a.title ?? 'notification'), 96) }),
  reconfigure: (a) => ({ icon: '⚙', headline: textPart(argKeys(a) || 'configuration') }),
  reorder_child: (a) => ({ icon: '↕', headline: cardPart(a.childId ?? a.id) }),
  restart_server: () => ({ icon: '↻', headline: textPart('restart server') }),
  stop_project: () => ({ icon: '■', headline: textPart('stop project') }),
  show_config: () => ({ icon: '⚙', headline: textPart('configuration') }),
  start_project: () => ({ icon: '▶', headline: textPart('start project') }),
  skill: (a) => ({ icon: '🪄', headline: textPart(str(a.name ?? a.skill ?? 'list skills')) }),
  mcp_tool_call: (a) => ({ icon: '🔌', headline: textPart(str(a.tool ?? a.name ?? 'mcp')), detail: textPart(a.params ?? a.arguments ?? '', 72) }),
  list_card_history: (a) => ({ icon: '🕘', headline: cardPart(a.cardId) }),
  get_card_history_entry: (a) => ({ icon: '🕘', headline: cardPart(a.cardId), detail: textPart(`v${str(a.version_seq)}`) }),
  diff_card: (a) => ({ icon: '🔀', headline: cardPart(a.cardId) }),
};

export const resultPresenters: Record<string, ResultPresenter> = {
  read: (ctx) => { const r = ctx.record; if (!r) return { headline: textPart(ctx.rawContent, 96) }; const entries = Array.isArray(r.entries) ? r.entries.length : null; if (entries !== null) return { headline: textPart(`${entries} entr${entries === 1 ? 'y' : 'ies'}`) }; const content = typeof r.content === 'string' ? r.content : ''; const lines = typeof r.total_lines === 'number' ? r.total_lines : content ? content.split('\n').length : 0; return { headline: textPart(lines ? `${lines} lines` : ctx.rawContent, 96) }; },
  write: (ctx) => { const bytes = typeof ctx.record?.bytes === 'number' ? ctx.record.bytes : null; return { headline: textPart(bytes !== null ? `wrote ${formatBytes(bytes)}` : 'wrote file') }; },
  glob: (ctx) => { const matches = Array.isArray(ctx.record?.matches) ? ctx.record!.matches.length : null; return { headline: matches !== null ? textPart(`${matches} match${matches === 1 ? '' : 'es'}`) : textPart(ctx.rawContent, 96) }; },
  grep: (ctx) => resultPresenters.glob(ctx),
  edit: (ctx) => ({ headline: textPart(`edited ${str(ctx.record?.path ?? 'file')}`) }),
  apply_patch: (ctx) => { const changed = Array.isArray(ctx.record?.changed_files) ? ctx.record!.changed_files.length : null; return { headline: textPart(changed !== null ? `patched ${changed} file${changed === 1 ? '' : 's'}` : 'patch applied') }; },
  websearch: (ctx) => { const results = Array.isArray(ctx.record?.results) ? ctx.record!.results.length : null; return { headline: textPart(results !== null ? `${results} result${results === 1 ? '' : 's'}` : ctx.rawContent, 96) }; },
  webfetch: (ctx) => ({ headline: textPart(str(ctx.record?.saved_as ?? ctx.record?.stash_url ?? ctx.record?.url ?? 'fetched'), 96) }),
  run_command: (ctx) => { const r = ctx.record; const exit = typeof r?.exit_code === 'number' ? r.exit_code : null; const status = typeof r?.status === 'string' ? r.status : null; const procId = typeof r?.process_id === 'string' ? r.process_id : null; const parts = []; if (exit !== null) parts.push(`exit ${exit}`); if (status) parts.push(status); return { headline: textPart(parts.length > 0 ? parts.join(' · ') : 'completed'), detail: procId ? textPart(`process ${procId}`) : undefined }; },
  wait_process: (ctx) => resultPresenters.run_command(ctx),
  kill_process: (ctx) => resultPresenters.run_command(ctx),
  activate_card: (ctx) => describeCardOutcome(ctx, 'activated'), cancel_card: (ctx) => describeCardOutcome(ctx, 'cancelled'), delete_card: (ctx) => describeCardOutcome(ctx, 'deleted'), create_card: (ctx) => describeCardOutcome(ctx, 'created'), edit_card: (ctx) => describeCardOutcome(ctx, 'edited'), move_card: (ctx) => describeCardOutcome(ctx, 'moved'),
  emit_result: (ctx) => ({ headline: textPart(str(ctx.record?.summary ?? ctx.record?.status ?? 'terminal result'), 96) }),
  get_card: (ctx) => { const card = asRecord(ctx.record?.card) ?? ctx.record; if (!card) return { headline: textPart(ctx.rawContent, 96) }; return { headline: textPart(str(card.title) || `card ${str(card.id)}`), detail: textPart([str(card.type), str(card.status)].filter(Boolean).join(' · ')) }; },
  list_cards: (ctx) => { const cards = Array.isArray(ctx.record?.cards) ? ctx.record!.cards : Array.isArray(ctx.parsed) ? ctx.parsed as unknown[] : null; return { headline: cards ? textPart(`${cards.length} card${cards.length === 1 ? '' : 's'}`) : textPart(ctx.rawContent, 96) }; },
  get_tree: () => ({ headline: textPart('tree fetched') }),
  navigate_workspace: () => ({ headline: textPart('workspace navigation queued') }), navigate_back: () => ({ headline: textPart('back navigation queued') }), queue_notification: () => ({ headline: textPart('notification queued') }),
  reconfigure: () => ({ headline: textPart('configuration updated') }), reorder_child: () => ({ headline: textPart('card reordered') }), restart_server: () => ({ headline: textPart('server restart requested') }), stop_project: () => ({ headline: textPart('project stopped') }), show_config: () => ({ headline: textPart('configuration loaded') }),
  start_project: () => ({ headline: textPart('project start requested') }),
  add_note: (ctx) => ({ headline: textPart(str(ctx.record?.noteId ?? ctx.record?.id) ? `note ${str(ctx.record?.noteId ?? ctx.record?.id)}` : 'note added') }),
  list_notes: (ctx) => { const notes = Array.isArray(ctx.record?.notes) ? ctx.record!.notes : null; return { headline: notes ? textPart(`${notes.length} note${notes.length === 1 ? '' : 's'}`) : textPart(ctx.rawContent, 96) }; },
  mark_note_handled: () => ({ headline: textPart('note handled') }),
  read_runtime_events: (ctx) => describeJsonlTail(ctx, 'events'), read_runtime_errors: (ctx) => describeJsonlTail(ctx, 'errors'), read_control_actions: (ctx) => describeJsonlTail(ctx, 'control actions'),
  list_processes_tool: (ctx) => { const list = Array.isArray(ctx.record?.processes) ? ctx.record!.processes : Array.isArray(ctx.parsed) ? ctx.parsed as unknown[] : null; return { headline: list ? textPart(`${list.length} process${list.length === 1 ? '' : 'es'}`) : textPart(ctx.rawContent, 96) }; },
  list_agent_sessions: (ctx) => { const list = Array.isArray(ctx.record?.sessions) ? ctx.record!.sessions : Array.isArray(ctx.parsed) ? ctx.parsed as unknown[] : null; return { headline: list ? textPart(`${list.length} session${list.length === 1 ? '' : 's'}`) : textPart(ctx.rawContent, 96) }; },
  read_agent_session: (ctx) => { const messages = Array.isArray(ctx.record?.messages) ? ctx.record!.messages : null; return { headline: messages ? textPart(`${messages.length} message${messages.length === 1 ? '' : 's'}`) : textPart(ctx.rawContent, 96) }; },
  skill: (ctx) => ({ headline: textPart(Array.isArray(ctx.record?.skills) ? `${ctx.record!.skills.length} skill${ctx.record!.skills.length === 1 ? '' : 's'}` : 'skill loaded') }),
  mcp_tool_call: (ctx) => ({ headline: textPart(ctx.record?.summary ?? ctx.record?.result ?? ctx.parsed ?? ctx.rawContent, 96) }),
};
