import { expect, it, vi } from 'vitest';

it('bootstrap, reconnect and card invalidation never request policy while retaining Cards ownership', async () => {
  vi.resetModules();
  const registerResource = vi.fn();
  const connect = vi.fn();
  const refetch = vi.fn(async () => undefined);
  const ensureRoot = vi.fn(async () => undefined);
  const onInvalidate = vi.fn();
  const onReconnect = vi.fn();
  const getContentPolicyRuntime = vi.fn();
  vi.doMock('../api/client', () => ({ getContentPolicyRuntime }));
  vi.doMock('../stores/sync', () => ({ useSyncStore: () => ({ registerResource, connect }) }));
  vi.doMock('../stores/runtime', () => ({ useRuntimeStore: () => ({ refetch }) }));
  vi.doMock('../stores/cards', () => ({ useCardStore: () => ({ ensureRoot, onInvalidate, onReconnect }) }));
  const { startAppBootstrap } = await import('../composables/useAppBootstrap');
  startAppBootstrap();
  startAppBootstrap();
  const cards = registerResource.mock.calls[0]![0];
  const target = { scope: 'detail', card_id: 'project' };
  cards.onInvalidate(target);
  cards.onReconnect();
  await Promise.resolve();
  expect(connect).toHaveBeenCalledTimes(1);
  expect(refetch).toHaveBeenCalledTimes(1);
  expect(ensureRoot).toHaveBeenCalledTimes(1);
  expect(onInvalidate).toHaveBeenCalledWith(target);
  expect(onReconnect).toHaveBeenCalledTimes(1);
  expect(registerResource.mock.calls.map(([item]) => item.resource)).toEqual(['cards', 'runtime']);
  expect(getContentPolicyRuntime).not.toHaveBeenCalled();
});
