import { describe, it, expect, vi, beforeEach } from 'vitest';
import { mount, flushPromises } from '@vue/test-utils';
import { createPinia, setActivePinia } from 'pinia';
import type { CardHistoryListResponse } from '../api/contracts';
import CardHistoryPanel from '../components/cards/CardHistoryPanel.vue';
import { useCardStore } from '../stores/cards';
import { cardView, historyCard } from './card-view-fixtures';
vi.mock('../api/client', async (importOriginal) => ({ ...(await importOriginal<typeof import('../api/client')>()), getCard: vi.fn(), listCardHistory: vi.fn(), getCardHistoryEntry: vi.fn(), getCardDiff: vi.fn() }));
import { listCardHistory, getCardHistoryEntry, getCardDiff, OperatorApiError } from '../api/client';
const CARD = 'card-a';
const snapshot = historyCard(CARD, { title: 'before', version_seq: 2 });
const entryId = '11111111-1111-4111-8111-111111111111';
const publishedAt = '2026-01-01T00:00:01.000Z';
const change = { summary: 'title updated', changed_fields: ['title' as const], actor: 'planner' as const };
const header = { entry_id: entryId, version: 2, published_at: publishedAt, artifact_kind: 'card-version' as const, change };
describe('CardHistoryPanel', () => {
  let pinia: ReturnType<typeof createPinia>;
  beforeEach(() => { vi.clearAllMocks(); pinia = createPinia(); setActivePinia(pinia); useCardStore().selectedDetail = { cardId: CARD, card: cardView(CARD, { title: 'after', version_seq: 3 }) }; });
  function success(): void { vi.mocked(listCardHistory).mockResolvedValue({ card_id: CARD, versions: [header], total: 1 }); vi.mocked(getCardHistoryEntry).mockResolvedValue({ card_id: CARD, version: 2, entry_id: entryId, published_at: publishedAt, artifact: { kind: 'card-version', card: snapshot, change } }); vi.mocked(getCardDiff).mockResolvedValue({ card_id: CARD, from: 2, to: 3, diff: [{ field: 'title', before: 'before', after: 'after' }] }); }
  it('renders ordinary metadata, recorded actor, snapshot, and current-relative diff', async () => { success(); const wrapper = mount(CardHistoryPanel, { props: { cardId: CARD }, global: { plugins: [pinia] } }); await flushPromises(); const text = wrapper.text(); expect(text).toContain('title updated'); expect(text).toContain('title'); expect(text).toContain('Changed by planner'); expect(text).toContain('Snapshot version'); expect(text).toContain('Published at'); expect(text).toContain('Diff vs current card'); expect(text).toContain('before'); expect(text).toContain('after'); expect(text).not.toContain('Reason'); });
  it('renders null metadata generically without inferring initial or queue activity', async () => { vi.mocked(listCardHistory).mockResolvedValue({ card_id: CARD, versions: [{ ...header, change: null }], total: 1 }); vi.mocked(getCardHistoryEntry).mockResolvedValue({ card_id: CARD, version: 2, entry_id: entryId, published_at: publishedAt, artifact: { kind: 'card-version', card: snapshot, change: null } }); vi.mocked(getCardDiff).mockResolvedValue({ card_id: CARD, from: 2, to: 3, diff: [] }); const wrapper = mount(CardHistoryPanel, { props: { cardId: CARD }, global: { plugins: [pinia] } }); await flushPromises(); const text = wrapper.text(); expect(text).toContain('Card version'); expect(text).toContain('No ordinary change metadata'); expect(text).not.toContain('queue'); expect(text).not.toContain('Initial card version'); expect(text).not.toContain('Changed by'); });
  it('renders mixed lifecycle metadata without a runtime actor or queue details', async () => { const mixed = { summary: 'lifecycle, status_text updated', changed_fields: ['lifecycle' as const, 'status_text' as const], actor: null }; vi.mocked(listCardHistory).mockResolvedValue({ card_id: CARD, versions: [{ ...header, change: mixed }], total: 1 }); vi.mocked(getCardHistoryEntry).mockResolvedValue({ card_id: CARD, version: 2, entry_id: entryId, published_at: publishedAt, artifact: { kind: 'card-version', card: snapshot, change: mixed } }); vi.mocked(getCardDiff).mockResolvedValue({ card_id: CARD, from: 2, to: 3, diff: [] }); const wrapper = mount(CardHistoryPanel, { props: { cardId: CARD }, global: { plugins: [pinia] } }); await flushPromises(); const text = wrapper.text(); expect(text).toContain('lifecycle, status_text updated'); expect(text).toContain('lifecycle, status_text'); expect(text).not.toContain('Changed by'); expect(text).not.toContain('pending_notifications'); expect(text).not.toContain('notification'); });
  it('renders loading then empty state', async () => { let resolveHistory: (value: CardHistoryListResponse) => void = () => {}; vi.mocked(listCardHistory).mockReturnValue(new Promise((resolve) => { resolveHistory = resolve; })); const wrapper = mount(CardHistoryPanel, { props: { cardId: CARD }, global: { plugins: [pinia] } }); await Promise.resolve(); expect(wrapper.text()).toContain('Loading card history…'); resolveHistory({ card_id: CARD, versions: [], total: 0 }); await flushPromises(); expect(wrapper.text()).toContain('No tracked card history'); });
  it('renders unauthorized and detail failures', async () => { vi.mocked(listCardHistory).mockRejectedValue(new OperatorApiError('cards.history.list', 401, { error: 'Unauthorized', statusCode: 401 })); const unauthorized = mount(CardHistoryPanel, { props: { cardId: CARD }, global: { plugins: [pinia] } }); await flushPromises(); expect(unauthorized.text()).toContain('Unauthorized'); unauthorized.unmount(); success(); vi.mocked(getCardHistoryEntry).mockRejectedValue(new Error('History detail failed')); const failed = mount(CardHistoryPanel, { props: { cardId: CARD }, global: { plugins: [pinia] } }); await flushPromises(); expect(failed.text()).toContain('History detail failed'); });
  it('redacts arbitrary secret-bearing diff values while snapshot remains canonical', async () => { success(); vi.mocked(getCardDiff).mockResolvedValue({ card_id: CARD, from: 2, to: 3, diff: [{ field: 'config_blob', before: 'Bearer very-secret-token', after: 'sk-updated-secret' }, { field: 'safe_field', before: 'before', after: 'after' }] }); const wrapper = mount(CardHistoryPanel, { props: { cardId: CARD }, global: { plugins: [pinia] } }); await flushPromises(); expect(wrapper.text()).toContain('[redacted]'); expect(wrapper.text()).not.toContain('very-secret-token'); expect(wrapper.text()).not.toContain('sk-updated-secret'); });
});
