export {
  ScopeDisposed,
  createResourceScope,
  type Disposable,
  type DisposalReport,
  type ResourceScope,
  type ScopedChildProcess,
  type ScopedFsWatch,
  type ScopedInterval,
  type ScopedListener,
  type ScopedSignalHandler,
  type ScopedTimeout,
  type SpawnOpts,
  type WatchHandler,
} from './resource-scope.js';
